# SPDX-FileCopyrightText: 2006-2025 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2025 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC-BY-4.0

name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * MON"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'OpenMS' || github.event_name == 'workflow_dispatch'
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build image
        working-directory: ./docker
        run: docker build . &> ${{ runner.temp }}/build-${{ github.run_id }}.log

      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.run_id }}.log
          path: ${{ runner.temp }}/build-${{ github.run_id }}.log

      - name: Show log
        if: always()
        run: cat ${{ runner.temp }}/build-${{ github.run_id }}.log
